# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ubuntu/polkalokr-migration-server
# permissions:
#   - object: /home/ubuntu
#     owner: ubuntu
#     group: ubuntu
#     type:
#       - directory
#       - file
# hooks:
#   ApplicationStop:
#     - location: scripts/terminate.sh
#       timeout: 300
#       runas: ubuntu
#   ApplicationStart:
#     - location: scripts/reload-pm2.sh
#       timeout: 300
#       runas: ubuntu
#   ValidateService:
#     - location: scripts/validate.sh
#       timeout: 300
#       runas: ubuntu